### ISSUE TITLE
launchd?

### ISSUE THREAD

**Issue by donmontalvo** [franton/Policy-Scripts#1]
Not really an issue, more of an inquiry. Do we have to unload the service too?

launchctl unload -w /System/Library/LaunchDaemons/com.apple.InternetSharing.plist

**Comment by franton** [comment]
In my testing, the code i've provided works just fine. To be fair, this particular script is now superseded by my CIS work at https://github.com/franton/CIS-Apple-Security-Casper/tree/master/2.4.2%20Disable%20Internet%20Sharing

I prefer not doing anything with launchctl and plists in /System . The changes are not reflected in the file due to SIP, so finding if they're running or disabled becomes nasty.
